# Generated by Django 4.1 on 2022-09-16 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appreview", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test",
                to="appreview.ticket",
            ),
        ),
        migrations.AlterField(
            model_name="ticket", name="image", field=models.ImageField(upload_to=""),
        ),
    ]
